version: "3.0"

services:
  #certbot:
  #image: certbot/certbot:v0.36.0
  #restart: unless-stopped
  #volumes:
  #- ./nginx/certbot/conf:/etc/letsencrypt
  #- ./nginx/certbot/www:/var/www/certbot
  #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  node:
    build: .
    #image: gagneet/adherelive:portal
    command: ["npm", "run", "dev"]
    ports:
      - "${WEB_SERVER_PORT}:5000"
      - "${REACT_SERVER_PORT}:3000"
    tty: true
    volumes:
      - ./:/usr/src/app
      - ./.node_env:/usr/src/app/.env
    links:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=adhere
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

## By default, this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  mysql:
    driver: local
