version: "3.0"

services:
  node:
    build:
      context: .
      dockerfile: docker/DockerfileDev
    restart: always
    command:
      - npm
      - run
      - dev
    ports:
      - 5000:5000
    logging:
      options:
        max-size: 150m
        max-file: "3"
    volumes:
      - ./:/usr/src/app
      - ./env_files/.node_env_demo:/usr/src/app/.env
    links:
      - mysql
      - mongo
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=1073741824
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=adhere
      - MYSQL_USER=adhere
      - MYSQL_PASSWORD=password

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - adhere_mongo:/data/db

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "3000:8080"
    depends_on:
      - mysql
volumes:
  mysql:
    driver: local
  adhere_mongo:
    driver: local