version: "3.0"

services:
  node:
    build: .
    ports:
      - "${WEB_SERVER_PORT}:5000"
      - "${REACT_SERVER_PORT}:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/usr/src/app
      - ./.node_env:/usr/src/app/.env
    links:
      - mongodb
      - minio1
      - minio2
      - minio3
      - minio4

  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
  ## minio stacks

  minio1:
    image: minio/minio
    volumes:
      - rpm_storage_stack1:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

  minio2:
    image: minio/minio
    volumes:
      - rpm_storage_stack2:/export
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

  minio3:
    image: minio/minio
    volumes:
      - rpm_storage_stack3:/export
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

  minio4:
    image: minio/minio
    volumes:
      - rpm_storage_stack4:/export
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  rpm_storage_stack1:
  rpm_storage_stack2:
  rpm_storage_stack3:
  rpm_storage_stack4:
