export default {
  WEB_URL: process.env.REACT_APP_WEB_URL,
  CHANNEL_SERVER: process.env.REACT_APP_TWILIO_CHANNEL_SERVER,
  algolia: {
    app_id: process.env.REACT_APP_ALOGLIA_APP_ID,
    app_key: process.env.REACT_APP_ALOGLIA_APP_KEY,
  },
  REACT_APP_ADMIN_MEDICINE_ONE_PAGE_LIMIT:
    process.env.REACT_APP_ADMIN_MEDICINE_ONE_PAGE_LIMIT,
  REACT_APP_PATIENT_TABLE_ONE_PAGE_LIMIT:
    process.env.REACT_APP_PATIENT_TABLE_ONE_PAGE_LIMIT,
  REACT_APP_NOTIFICATION_ONE_TIME_LIMIT:
    process.env.REACT_APP_NOTIFICATION_ONE_TIME_LIMIT,
};
