# docker-compose.yml
version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://api-service:3000
    ports:
      - "3000:3000"
    networks:
      - app-network

  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - TEMP_DIR=/tmp/pdfs
      - REACT_APP_URL=http://react-app:3000
    volumes:
      - pdf-temp:/tmp/pdfs
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - redis-service

  redis-service:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: overlay

volumes:
  redis-data:
  pdf-temp: