version: "3.0"

services:
  node:
    build:
      context: .
    restart: always
    command:
      - npm
      - run
      - start
    ports:
      - "${WEB_SERVER_PORT}:5000"
      - "${REACT_SERVER_PORT}:3000"
    logging:
      options:
        max-size: 150m
        max-file: "3"
    tty: true
    volumes:
      - ./:/usr/src/app
      - ./.node_env:/usr/src/app/.env
    links:
      #- mysql
      #- mongo
      - minio1
      - minio2
      - minio3
      - minio4

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - adhere_mongo:/data/db

  minio1:
    image: minio/minio
    volumes:
      - adhere_storage_stack1:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

  minio2:
    image: minio/minio
    volumes:
      - adhere_storage_stack2:/export
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

  minio3:
    image: minio/minio
    volumes:
      - adhere_storage_stack3:/export
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

  minio4:
    image: minio/minio
    volumes:
      - adhere_storage_stack4:/export
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: server http://minio{1...4}/export

## By default, this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  adhere_storage_stack1: null
  adhere_storage_stack2: null
  adhere_storage_stack3: null
  adhere_storage_stack4: null
  adhere_mongo:
    driver: local