import { USER_CATEGORY } from "../../../constant";

import PERMISSIONS from "../../../config/permissions";

export const getPermissions = type => {
  switch (type) {
    case USER_CATEGORY.ADMIN:
      return [
        PERMISSIONS.MEDICATIONS.ADD,
        PERMISSIONS.MEDICATIONS.UPDATE,
        PERMISSIONS.MEDICATIONS.VIEW,
        PERMISSIONS.MEDICATIONS.VIEW_TIMELINE,
        PERMISSIONS.MEDICATIONS.DELETE,
        PERMISSIONS.MEDICATIONS.TEMPLATE,

        PERMISSIONS.APPOINTMENTS.ADD,
        PERMISSIONS.APPOINTMENTS.UPDATE,
        PERMISSIONS.APPOINTMENTS.VIEW,
        PERMISSIONS.APPOINTMENTS.DELETE,

        PERMISSIONS.PATIENTS.ADD,
        PERMISSIONS.PATIENTS.UPDATE,
        PERMISSIONS.PATIENTS.VIEW,

        PERMISSIONS.CARE_PLAN.ADD,
        PERMISSIONS.CARE_PLAN.UPDATE,
        PERMISSIONS.CARE_PLAN.VIEW,

        PERMISSIONS.GRAPHS.ADD,
        PERMISSIONS.GRAPHS.UPDATE,

        PERMISSIONS.ACCOUNT.VERIFIED,

        PERMISSIONS.PAYMENT_PRODUCT.VIEW,

        PERMISSIONS.REPORTS.ADD,
        PERMISSIONS.REPORTS.UPDATE,
        PERMISSIONS.REPORTS.DELETE,
        PERMISSIONS.REPORTS.VIEW,

        PERMISSIONS.VITALS.ADD,
        PERMISSIONS.VITALS.UPDATE,
        PERMISSIONS.VITALS.DELETE,
        PERMISSIONS.VITALS.VIEW,
        PERMISSIONS.VITALS.TEMPLATE,

        PERMISSIONS.WORKOUTS.ADD,
        PERMISSIONS.WORKOUTS.UPDATE,
        PERMISSIONS.WORKOUTS.DELETE,
        PERMISSIONS.WORKOUTS.VIEW,
        PERMISSIONS.WORKOUTS.TEMPLATE,

        PERMISSIONS.DIETS.ADD,
        PERMISSIONS.DIETS.UPDATE,
        PERMISSIONS.DIETS.DELETE,
        PERMISSIONS.DIETS.VIEW,
        PERMISSIONS.DIETS.TEMPLATE
      ];
    case USER_CATEGORY.DOCTOR:
      return [
        PERMISSIONS.MEDICATIONS.ADD,
        PERMISSIONS.MEDICATIONS.UPDATE,
        PERMISSIONS.MEDICATIONS.VIEW,
        PERMISSIONS.MEDICATIONS.VIEW_TIMELINE,
        PERMISSIONS.MEDICATIONS.DELETE,
        PERMISSIONS.MEDICATIONS.TEMPLATE,

        PERMISSIONS.APPOINTMENTS.ADD,
        PERMISSIONS.APPOINTMENTS.UPDATE,
        PERMISSIONS.APPOINTMENTS.VIEW,
        PERMISSIONS.APPOINTMENTS.DELETE,

        PERMISSIONS.PATIENTS.ADD,
        PERMISSIONS.PATIENTS.UPDATE,
        PERMISSIONS.PATIENTS.VIEW,

        PERMISSIONS.CARE_PLAN.ADD,
        PERMISSIONS.CARE_PLAN.UPDATE,
        PERMISSIONS.CARE_PLAN.VIEW,
        PERMISSIONS.CARE_PLAN.ADD_PROFILE,

        PERMISSIONS.CARE_PLAN_TEMPLATE.ADD,
        PERMISSIONS.CARE_PLAN_TEMPLATE.UPDATE,
        PERMISSIONS.CARE_PLAN_TEMPLATE.VIEW,
        PERMISSIONS.CARE_PLAN_TEMPLATE.DUPLICATE,
        PERMISSIONS.CARE_PLAN_TEMPLATE.DELETE,

        PERMISSIONS.GRAPHS.ADD,
        PERMISSIONS.GRAPHS.UPDATE,

        PERMISSIONS.ACCOUNT.VERIFIED,

        PERMISSIONS.PAYMENT_PRODUCT.VIEW,

        PERMISSIONS.REPORTS.ADD,
        PERMISSIONS.REPORTS.UPDATE,
        PERMISSIONS.REPORTS.DELETE,
        PERMISSIONS.REPORTS.VIEW,

        PERMISSIONS.VITALS.ADD,
        PERMISSIONS.VITALS.UPDATE,
        PERMISSIONS.VITALS.DELETE,
        PERMISSIONS.VITALS.VIEW,

        PERMISSIONS.WORKOUTS.ADD,
        PERMISSIONS.WORKOUTS.UPDATE,
        PERMISSIONS.WORKOUTS.DELETE,
        PERMISSIONS.WORKOUTS.VIEW,

        PERMISSIONS.DIETS.ADD,
        PERMISSIONS.DIETS.UPDATE,
        PERMISSIONS.DIETS.DELETE,
        PERMISSIONS.DIETS.VIEW
      ];

    case USER_CATEGORY.HSP:
      return [
        PERMISSIONS.MEDICATIONS.VIEW,
        PERMISSIONS.MEDICATIONS.VIEW_TIMELINE,

        PERMISSIONS.APPOINTMENTS.ADD,
        PERMISSIONS.APPOINTMENTS.UPDATE,
        PERMISSIONS.APPOINTMENTS.VIEW,
        PERMISSIONS.APPOINTMENTS.DELETE,

        PERMISSIONS.PATIENTS.ADD,
        PERMISSIONS.PATIENTS.UPDATE,
        PERMISSIONS.PATIENTS.VIEW,

        PERMISSIONS.CARE_PLAN.ADD,
        PERMISSIONS.CARE_PLAN.UPDATE,
        PERMISSIONS.CARE_PLAN.VIEW,
        PERMISSIONS.CARE_PLAN.ADD_PROFILE,

        PERMISSIONS.CARE_PLAN_TEMPLATE.ADD,
        PERMISSIONS.CARE_PLAN_TEMPLATE.UPDATE,
        PERMISSIONS.CARE_PLAN_TEMPLATE.VIEW,
        PERMISSIONS.CARE_PLAN_TEMPLATE.DUPLICATE,
        PERMISSIONS.CARE_PLAN_TEMPLATE.DELETE,

        PERMISSIONS.GRAPHS.ADD,
        PERMISSIONS.GRAPHS.UPDATE,

        PERMISSIONS.ACCOUNT.VERIFIED,

        PERMISSIONS.PAYMENT_PRODUCT.VIEW,

        PERMISSIONS.REPORTS.ADD,
        PERMISSIONS.REPORTS.UPDATE,
        PERMISSIONS.REPORTS.DELETE,
        PERMISSIONS.REPORTS.VIEW,

        PERMISSIONS.VITALS.ADD,
        PERMISSIONS.VITALS.UPDATE,
        PERMISSIONS.VITALS.DELETE,
        PERMISSIONS.VITALS.VIEW,

        PERMISSIONS.WORKOUTS.ADD,
        PERMISSIONS.WORKOUTS.UPDATE,
        PERMISSIONS.WORKOUTS.DELETE,
        PERMISSIONS.WORKOUTS.VIEW,

        PERMISSIONS.DIETS.ADD,
        PERMISSIONS.DIETS.UPDATE,
        PERMISSIONS.DIETS.DELETE,
        PERMISSIONS.DIETS.VIEW
      ];
    case USER_CATEGORY.PROVIDER:
      return [
        PERMISSIONS.MEDICATIONS.VIEW,
        PERMISSIONS.MEDICATIONS.VIEW_TIMELINE,

        PERMISSIONS.APPOINTMENTS.ADD,
        PERMISSIONS.APPOINTMENTS.UPDATE,
        PERMISSIONS.APPOINTMENTS.VIEW,
        PERMISSIONS.APPOINTMENTS.DELETE,

        PERMISSIONS.DOCTORS.ADD,
        PERMISSIONS.DOCTORS.UPDATE,
        PERMISSIONS.DOCTORS.VIEW,

        PERMISSIONS.PATIENTS.ADD,
        PERMISSIONS.PATIENTS.UPDATE,
        PERMISSIONS.PATIENTS.VIEW,

        PERMISSIONS.CARE_PLAN.ADD,
        PERMISSIONS.CARE_PLAN.UPDATE,
        PERMISSIONS.CARE_PLAN.VIEW,
        PERMISSIONS.CARE_PLAN.ADD_PROFILE,

        PERMISSIONS.GRAPHS.ADD,
        PERMISSIONS.GRAPHS.UPDATE,

        PERMISSIONS.ACCOUNT.VERIFIED,

        PERMISSIONS.PAYMENT_PRODUCT.VIEW,
        PERMISSIONS.PAYMENT_PRODUCT.ADD
      ];
    case USER_CATEGORY.PATIENT:
      return [
        PERMISSIONS.MEDICATIONS.VIEW,
        PERMISSIONS.MEDICATIONS.VIEW_TIMELINE,

        PERMISSIONS.APPOINTMENTS.VIEW,

        PERMISSIONS.CARE_PLAN.VIEW,

        PERMISSIONS.ACCOUNT.VERIFIED,

        PERMISSIONS.PAYMENT_PRODUCT.VIEW
      ];
  }
};
