# Update Ubuntu Software repository and install dependencies
RUN apt update && apt upgrade -y
RUN apt install -y build-essential

# Install dependencies for NVM and Node.js
RUN apt update && apt install -y curl git bash

# Install GCC & make
RUN apt install -y gcc g++ make
RUN apt install -y libglib2.0-0
RUN apt install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon-x11-0 libxcomposite1 libxdamage1 libxrandr2 libgbm-dev
RUN apt-get install -y dconf-service libasound2t64 libc6 libcairo2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxext6 libxfixes3 libxi6 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation lsb-release xdg-utils wget libxshmfence-dev

# Install Node.js using nvm to ensure the latest version is used
RUN apt install -y nodejs npm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash

# Configure NVM in .bashrc
ENV NVM_DIR=/root/.nvm
RUN echo 'export NVM_DIR="$HOME/.nvm"' >> /root/.bashrc && \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> /root/.bashrc && \
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> /root/.bashrc

# Source nvm and install Node.js
RUN bash -c "source /root/.nvm/nvm.sh && \
    nvm install 18 && \
    nvm use 18 && \
    nvm alias default 18 && \
    npm install -g npm"

# Ensure Node.js and npm are in PATH
ENV PATH="/root/.nvm/versions/node/v18.19.1/bin:${PATH}"

# Debugging: Verify Node.js installation
RUN which node
RUN echo $PATH
RUN bash -c "source /root/.nvm/nvm.sh && nvm list"

# Verify Node.js and npm installation
RUN bash -c "source /root/.nvm/nvm.sh && node -v && npm -v"

# Set npm registry
RUN bash -c "source /root/.nvm/nvm.sh && npm config set registry https://registry.npmjs.org/ --global"

# Clean up
RUN rm -rf /var/lib/apt/lists/*
RUN apt clean