export default {
  /* [A] */

  APPOINTMENTS: {
    ADD: "ADD_APPOINTMENT",
    UPDATE: "UPDATE_APPOINTMENT",
    VIEW: "VIEW_APPOINTMENT",
    DELETE: "DELETE_APPOINTMENT",
    TEMPLATE: "TEMPLATE_APPOINTMENT"
  },

  ACCOUNT: {
    VERIFIED: "VERIFIED_ACCOUNT"
  },

  /* [C] */

  CARE_PLAN: {
    ADD: "ADD_CARE_PLAN",
    UPDATE: "UPDATE_CARE_PLAN",
    VIEW: "VIEW_CARE_PLAN"
  },

  CARE_PLAN_TEMPLATE: {
    ADD: "ADD_CARE_PLAN_TEMPLATE",
    UPDATE: "UPDATE_CARE_PLAN_TEMPLATE",
    VIEW: "VIEW_CARE_PLAN_TEMPLATE",
    DUPLICATE: "DUPLICATE_CARE_PLAN_TEMPLATE",
    DELETE: "DELETE_CARE_PLAN_TEMPLATE"
  },

  CALENDER: {
    VIEW: "VIEW_CALENDER"
  },

  /* [D] */

  DIETS: {
    ADD: "ADD_DIET",
    UPDATE: "UPDATE_DIET",
    VIEW: "VIEW_DIET",
    DELETE: "DELETE_DIET",
    TEMPLATE: "TEMPLATE_DIET"
  },

  DOCTORS: {
    ADD: "ADD_DOCTOR",
    UPDATE: "UPDATE_DOCTOR",
    VIEW: "VIEW_DOCTOR"
  },

  /* [G] */

  GRAPHS: {
    ADD: "ADD_GRAPH",
    UPDATE: "UPDATE_GRAPH"
  },

  /* [M] */

  MEDICATIONS: {
    ADD: "ADD_MEDICATION",
    UPDATE: "UPDATE_MEDICATION",
    VIEW: "VIEW_MEDICATION",
    VIEW_TIMELINE: "VIEW_TIMELINE_MEDICATION",
    DELETE: "DELETE_MEDICATION",
    TEMPLATE: "TEMPLATE_MEDICATION"
  },

  /* [P] */

  PATIENTS: {
    ADD: "ADD_PATIENT",
    UPDATE: "UPDATE_PATIENT",
    VIEW: "VIEW_PATIENT"
  },

  PAYMENT_PRODUCT: {
    ADD: "ADD_PAYMENT_PRODUCT",
    VIEW: "VIEW_PAYMENT_PRODUCT"
  },

  /* [R] */

  REPORTS: {
    ADD: "ADD_REPORT",
    UPDATE: "UPDATE_REPORT",
    VIEW: "VIEW_REPORT",
    DELETE: "DELETE_REPORT"
  },

  /* [V] */

  VITALS: {
    ADD: "ADD_VITAL",
    UPDATE: "UPDATE_VITAL",
    VIEW: "VIEW_VITAL",
    DELETE: "DELETE_VITAL",
    TEMPLATE: "TEMPLATE_VITAL"
  },

  /* [W] */

  WORKOUTS: {
    ADD: "ADD_WORKOUT",
    UPDATE: "UPDATE_WORKOUT",
    VIEW: "VIEW_WORKOUT",
    DELETE: "DELETE_WORKOUT",
    TEMPLATE: "TEMPLATE_WORKOUT"
  }
};

// export const USER_PERMISSIONS = {
//   [USER_CATEGORY.DOCTOR]: [
//     PERMISSIONS.MEDICATIONS.ADD,
//     PERMISSIONS.MEDICATIONS.UPDATE,
//     PERMISSIONS.MEDICATIONS.VIEW,
//     PERMISSIONS.MEDICATIONS.VIEW_TIMELINE,
//     PERMISSIONS.MEDICATIONS.DELETE,

//   ],

//   [USER_CATEGORY.HSP]: [
//     PERMISSIONS.MEDICATIONS.VIEW,
//     PERMISSIONS.MEDICATIONS.VIEW_TIMELINE,
//   ],
// };
